package com.tink.link.ui.analytics.models

internal enum class ApplicationEvent {
    INITIALIZED_WITHOUT_PROVIDER,
    INITIALIZED_WITH_PROVIDER,
    CREDENTIALS_SUBMITTED,
    PROVIDER_AUTHENTICATION_INITIALIZED,
    CREDENTIALS_VALIDATION_FAILED,
    AUTHENTICATION_SUCCESSFUL
}
