steps:
  - name: ':gradle: Lint'
    command: .buildkite/run-lint.sh
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: .buildkite/docker-compose.gradle.yml
  - name: ':gradle: Build'
    command: .buildkite/run-assemble.sh
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: .buildkite/docker-compose.gradle.yml
  - name: ':gradle: Tests'
    command: .buildkite/run-tests.sh
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: .buildkite/docker-compose.gradle.yml
  - name: ':male-detective: run detect-secrets on new commits'
    plugins:
    - docker#v3.3.0:
        image: gcr.io/tink-containers/detect-secrets:v1.1.0
        command: ["/opt/detect-secrets", "development"]
        always-pull: true
