steps:
  - name: ':gradle: Lint'
    command: .buildkite/run-lint.sh
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: .buildkite/docker-compose.gradle.yml
  - name: ':gradle: Build'
    command: .buildkite/run-assemble-debug.sh
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: .buildkite/docker-compose.gradle.yml
  - name: ':gradle: Tests'
    command: .buildkite/run-tests.sh
    plugins:
      docker-compose#v2.5.1:
        run: app
        config: .buildkite/docker-compose.gradle.yml
